-- Add additional metadata columns to tracks table
ALTER TABLE tracks ADD COLUMN IF NOT EXISTS album TEXT;
ALTER TABLE tracks ADD COLUMN IF NOT EXISTS year INTEGER;
ALTER TABLE tracks ADD COLUMN IF NOT EXISTS genre TEXT;
ALTER TABLE tracks ADD COLUMN IF NOT EXISTS composer TEXT;
ALTER TABLE tracks ADD COLUMN IF NOT EXISTS bpm INTEGER;
ALTER TABLE tracks ADD COLUMN IF NOT EXISTS key TEXT;
ALTER TABLE tracks ADD COLUMN IF NOT EXISTS isrc TEXT;
ALTER TABLE tracks ADD COLUMN IF NOT EXISTS copyright TEXT;
ALTER TABLE tracks ADD COLUMN IF NOT EXISTS comment TEXT;
